[package]
name = "rootbeer-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rb"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
rootbeer-core = { path = "../rootbeer-core" }
